### ISSUE TITLE
Dockerfile of Wordpress using FROM alpine: 3.17 produces error 

### ISSUE THREAD

**Issue by qduong42** [codesshaman/inception#4]
User
ERROR: Service 'wordpress' failed to build: The command '/bin/sh -c apk update && apk upgrade && apk add --no-cache     php8    php8-fpm  php8-mysqli     php8-json       php8-curl       php8-dom        php8-exif       php8-fileinfo   php8-mbstring   php8-openssl      php8-xml        php8-zip     php8-redis     wget     unzip &&   sed -i "s|listen = 127.0.0.1:9000|listen = 9000|g" /etc/php8/php-fpm.d/www.conf &&     sed -i "s|;listen.owner = nobody|listen.owner = nobody|g" /etc/php8/php-fpm.d/www.conf &&     sed -i "s|;listen.group = nobody|listen.group = nobody|g" /etc/php8/php-fpm.d/www.conf &&     rm -f /var/cache/apk/*' returned a non-zero code: 13

**Comment by gustavdlima** [comment]
You just need use the php 81 version, @qduong42

**Comment by qduong42** [comment]
passed the project and successfully adapted tutorial to work for alpine:3.17 :)
